### ISSUE TITLE
Cannot find "stdstar_lookup_table.dat"

### ISSUE THREAD

**Issue by clidman** [PyWiFeS/pipeline#34]
python3 reduce_data.py 20231111
Traceback (most recent call last):
  File "/Users/clidman/Official/Students/Internship/Spectra/Data/reduce_data.py", line 12, in <module>
    from pywifes.data_classifier import classify
  File "/Users/clidman/opt/anaconda3/envs/PyWiFeS/lib/python3.12/site-packages/pywifes/__init__.py", line 3, in <module>
    from . import data_classifier, js_wifes_adr, lacosmic, mpfit, optical_model, pywifes, v06_wifes_adr, wifes_adr, wifes_calib, wifes_ephemeris, wifes_imtrans, wifes_metadata, wifes_wsol, working_updated_wifes_calib
  File "/Users/clidman/opt/anaconda3/envs/PyWiFeS/lib/python3.12/site-packages/pywifes/data_classifier.py", line 5, in <module>
    from . import wifes_calib
  File "/Users/clidman/opt/anaconda3/envs/PyWiFeS/lib/python3.12/site-packages/pywifes/wifes_calib.py", line 18, in <module>
    f1 = open(stdstar_fn, 'r')
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/clidman/opt/anaconda3/envs/PyWiFeS/lib/python3.12/site-packages/pywifes/../../reference_data/stdstar_lookup_table.dat'

**Comment by timothyfrankdavies** [comment]
Hi Chris, that's a change I didn't communicate very well and should add documentation for.

I mentioned it here: https://github.com/PyWiFeS/pipeline/pull/24

If you install with pip install, the reference_data directory doesn't get installed with it. So you either need to install in editable mode with `pip install -e .`,  or you need to set the environment variable `PYWIFES_DIR`, e.g. using `export PYWIFES_DIR=...pipeline/reference_data/`

**Comment by CMartinezLombilla** [comment]
Thank you for reporting the issue, @clidman. Please, let us know if the pipeline runs smoothly after this amendment. We'll add this info to the `README.md` file.

**Comment by CMartinezLombilla** [comment]
The README.md has been updated so should be clear no how to proceed. As I said, please @clidman let us know if the pipeline works for you now. Thank you for reporting!
