### ISSUE TITLE
Pipeline will not run without OBJECT files

### ISSUE THREAD

**Issue by clidman** [PyWiFeS/pipeline#41]
The pipeline will return an error if there are files with IMAGETYP=OBJECT.

python3 reduce_data.py my_raw_data     
Traceback (most recent call last):
  File "/Users/clidman/Observatories/SSO/2.3M/Instruments/WiFES/2.3m_comp/intern_folder/reduce_data.py", line 856, in <module>
    main()
  File "/Users/clidman/Observatories/SSO/2.3M/Instruments/WiFES/2.3m_comp/intern_folder/reduce_data.py", line 47, in main
    sci_filename = obs_metadatas[arm]['sci'][0]['sci'][0]+'.fits'

It would be useful to run the pipeline without science frames so that calibration products can still be produced.

**Comment by CMartinezLombilla** [comment]
Hi Chris, thank you for reporting this issue. Ok, we'll fix it after the Christmas break. This should be easy to implement... Maybe add a reduction mode called 'cal' or something like with a new `.JSON` file so it only processes the calibration files. I'll keep you updated.

**Comment by CMartinezLombilla** [comment]
Hi @clidman, sorry that it took us a lot of time to come back to this issue. Just wanted to let you know that @felipeji is working on it and has it almost solved. We'll let you know once it's done.

**Comment by CMartinezLombilla** [comment]
Hi @clidman! We've updated the [automation](https://github.com/PyWiFeS/pipeline/tree/automation) branch so the pipeline is now able to run with just the calibration data (see instructions in the readme file) and generates the master calibration files. Please, give it a try if you can and let us know how it goes so I can close the issue.

**Comment by CMartinezLombilla** [comment]
@clidman, after some more tests, this implementation seems to be working fine. I'll close the issue then. If something comes up retaled to this, please let us know.
