### ISSUE TITLE
JSON file - params_class_R3000.json

### ISSUE THREAD

**Issue by clidman** [PyWiFeS/pipeline#69]
The following code snippet      

 {
            "step": "flat_response",
            "run": true,
            "suffix": null,
            "args": {
                "mode": "dome"
            }

should be chnaged to 

       {
            "step": "flat_response",
            "run": true,
            "suffix": null,
            "args": {
                "mode": "all"
            }

**Comment by felipeji** [comment]
Changed in commit e135c4db8b034b0a67d24c9a86d90daab8094de6 (automation).
